### ISSUE TITLE
Fix navigation dropdown

### ISSUE THREAD

**Issue by wotta** [wotta/woutervm_next#74]
Currently there have been some changes that are breaking the dropdown navigation on mobile.

This should be an easy fix.

**Comment by akashyadav24** [comment]
i would like work on it

**Comment by wotta** [comment]
Heej @akashyadav24,

My bad I just noticed that you wanted to pick this up.
I've fixed it already. If you ever want to pick something up that you'll be able to fix you're free to do.

Since this is my personal website project I tend to create tickets on the fly and pick them up or create inspirational tickets.
